name: "Code Quality using PMD"
description: "An action to rate the code quality"

inputs:
  quality:
    description: "percentage code quality"
    required: true

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: "Check the ruleset with PMD"
      uses: pmd/pmd-github-action@v2
      id: pmd
      with:
        uploadSarifReport: true
        analyzeModifiedFilesOnly: false
        rulesets: "${{ github.action_path }}/ruleset.xml"

    - name: Calculate Lines of Code
      shell: bash
      run: |
        total_lines=$(find src/ -name '*.java' -print0 | xargs -0 wc -l | awk '{total += $1} END {print total}')
        echo "total=$total_lines" >> $GITHUB_ENV
      
    - name: Calculate the code quality base on previous results.
      shell: bash
      run: |
        quality_score=$((100 - (violations / total * 100)))
        echo -e "Detailled score\nviolations: $violations\ntotal: $total\nquality: $quality_score"
        if [ "$quality_score" -lt $quality ]; then
          echo "Code quality is below the limit. Failing the build."
          exit 1
        fi
      env:
        violations: ${{ steps.pmd.outputs.violations }}
        quality: ${{ inputs.quality }}