# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
env:
  PRE_BUILD_COMMAND: git config --global --add safe.directory /github/workspace

name: code_quality_pmd

on:
  workflow_call:
    inputs:
      quality:
        required: true
        type: number
  
jobs:
  pmd-code-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
   
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: "Check the ruleset with PMD"
        uses: pmd/pmd-github-action@v2
        id: pmd
        with:
          uploadSarifReport: true
          analyzeModifiedFilesOnly: false
          rulesets: './ruleset.xml'

      - name: Calculate Lines of Code
        run: |
          total_lines=$(find src/ -name '*.java' -print0 | xargs -0 wc -l | awk '{total += $1} END {print total}')
          echo "total=$total_lines" >> $GITHUB_ENV
        
      - name: Calculate the code quality base on previous results.
        env:
          violations: ${{ steps.pmd.outputs.violations }}
          quality: ${{ inputs.quality }}
        run: |
          quality_score=$((100 - (violations / total * 100)))
          echo -e "Detailled score\nviolations: $violations\ntotal: $total\nquality: $quality_score"
          if [ "$quality_score" -lt $quality ]; then
            echo "Code quality is below the limit. Failing the build."
            exit 1
          fi
